language: generic
addons:
  apt:
    packages:
      - libc6:i386
      - libstdc++6:i386
env:
  global:
    - IDE_VERSION=1.8.5
before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - arduino --pref "boardsmanager.additional.urls=https://sandeepmistry.github.io/arduino-nRF5/package_nRF5_boards_index.json" --install-boards sandeepmistry:nRF5 > /dev/null
  - buildExampleSketch() { arduino --verbose-build --verify --board $1 $HOME/arduino-ide/examples/$2/$3/$3.ino; }
install:
  - mkdir -p $HOME/Arduino/hardware/sandeepmistry
  - ln -s $PWD $HOME/Arduino/hardware/sandeepmistry/nRF5
script:
  - buildExampleSketch sandeepmistry:nRF5:nRF52DK 01.Basics Blink
  - buildExampleSketch sandeepmistry:nRF5:BLENano:version=1_0 01.Basics Blink
  - buildExampleSketch sandeepmistry:nRF5:BBCmicrobit 01.Basics Blink
  - buildExampleSketch sandeepmistry:nRF5:BBCmicrobitV2 01.Basics Blink
